sudo: required
services:
  - docker

before_install:
  - docker build -t akshayagathia/emoji-search -f Dockerfile.dev .

script:
  - docker run akshayagathia/emoji-search npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "dockerapp"
  env: "Dockerapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-611793618815"
  bucker_path: "reactapp"
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  on:
    branch: master
